name: C0-in-C0 Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install cc0
      run: |
        wget https://c0.cs.cmu.edu/downloads/cc0-debian.deb
        sudo apt install ./cc0-debian.deb

    - name: Compile
      run: make

    - name: Run Tests
      run: make test
